---
# Implement your Workload deployment tasks here

- name: Setting up workload for user
  debug:
    msg: "Setting up workload for user ocp_username = {{ ocp_username }}"

- name: Install OpenShift GitOps operator
  include_role:
    name: install_operator
  vars:
    install_operator_action: install
    install_operator_name: openshift-gitops-operator
    install_operator_namespace: openshift-operators
    install_operator_channel: "{{ ocp4_workload_openshift_gitops_channel }}"
    install_operator_catalog: redhat-operators
    install_operator_automatic_install_plan_approval: "{{ ocp4_workload_openshift_gitops_automatic_install_plan_approval | default(true) }}"
    install_operator_starting_csv: "{{ ocp4_workload_openshift_gitops_starting_csv }}"
    install_operator_catalogsource_setup: "{{ ocp4_workload_openshift_gitops_use_catalog_snapshot | default(false)}}"
    install_operator_catalogsource_name: "{{ ocp4_workload_openshift_gitops_catalogsource_name | default('') }}"
    install_operator_catalogsource_namespace: openshift-operators
    install_operator_catalogsource_image: "{{ ocp4_workload_openshift_gitops_catalog_snapshot_image | default('') }}"
    install_operator_catalogsource_image_tag: "{{ ocp4_workload_openshift_gitops_catalog_snapshot_image_tag | default('') }}"

- name: Grant cluster-admin permissions to Gitops Service account
  when: ocp4_workload_openshift_gitops_setup_cluster_admin | bool
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'clusterrolebinding.yaml' ) | from_yaml }}"

- name: Update resources for openshift-gitops ArgoCD instance
  when: ocp4_workload_openshift_gitops_update_resources | bool
  block:
  - name: Wait until openshift-gitops ArgoCD instance has been created
    kubernetes.core.k8s_info:
      api_version: argoproj.io/v1alpha1
      kind: ArgoCD
      name: openshift-gitops
      namespace: openshift-gitops
    register: r_openshift_gitops
    until:
    - r_openshift_gitops is defined
    - r_openshift_gitops.resources is defined
    - r_openshift_gitops.resources | length == 1

  - name: Update resources for the openshift-gitops ArgoCD instance
    kubernetes.core.k8s:
      state: patched
      definition: "{{ lookup('template', 'openshift-gitops.yaml.j2' ) | from_yaml }}"

- name: Print access information
  when: ocp_workload_openshift_gitops_enable_access_details | bool 
  block:
  - name: Retrieve created route
    k8s_facts:
      api_version: "route.openshift.io/v1"
      kind: Route
      name: openshift-gitops-server
      namespace: openshift-gitops
    register: r_argocd_route

  - name: Retrieve aap secret
    k8s_facts:
      api_version: "v1"
      kind: Secret
      name: openshift-gitops-cluster
      namespace: openshift-gitops
    register: r_argocd_secret

  - name: Get automation_controller route hostname
    set_fact:
      _openshift_gitops_server_url: "{{ r_argocd_route.resources[0].spec.host }}"
      _openshift_gitops_admin_user: "{{ ocp4_workload_openshift_gitops_admin_user_name | default('admin') }}"
      _openshift_gitops_admin_password: "{{ r_argocd_secret.resources[0]['data']['admin.password'] |string |b64decode }}"

  - name: Print Access information
    agnosticd_user_info:
      data:
        openshift_gitops_server_url: "https://{{ _openshift_gitops_server_url }}"
        openshift_gitops_user: "{{ _openshift_gitops_admin_user }}"
        openshift_gitops_password: "{{ _openshift_gitops_admin_password }}"

# Leave this as the last task in the playbook.
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool
