---
vmc_project_name: "{{ env_type }}-{{ guid }}"
# SSH keys
vmc_ssh_key_path: "{{ output_dir }}/{{ guid }}_id_rsa"
vmc_ssh_pub_key_path: "{{ output_dir }}/{{ guid }}_id_rsa.pub"

# Naming of instances
vmc_instance_numeration: '%d'
vmc_vcenter_student_ip: ""

publicips: []
