---
- openstack.cloud.server:
    project_id: 89b497ee-5afc-420a-8fb5-56984898f4df
    hostnames: myserver
    tags: ci-xyz
    operating_system: ubuntu_16_04
    plan: baremetal_0
    facility: sjc1

- when: ACTION == 'provision'
  block:
    - include_tasks: create_project.yaml
    - include_tasks: ssh_key.yaml
    - include_tasks: create_instances.yaml

- when: ACTION == 'destroy'
  block:
    - include_tasks: lookup_project.yaml
    - when: equinix_metal_project_id is defined
      block:
        - include_tasks: delete_instances.yaml
        - include_tasks: delete_project.yaml

- when: ACTION in ['status', 'start', 'stop']
  block:
    - include_tasks: lookup_project.yaml
    - when: equinix_metal_project_id is defined
      block:
        - include_tasks: "{{ ACTION }}_instances.yaml"
