---
- name: Step 004 Environment specific Software
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - debug:
        msg: "Software tasks Started"

- name: Deploy OCP if IPI is defined
  hosts: bastion-vm
  tasks:
    - name: deploy OCP
      include_role:
        name: ocp4_aio_deploy_ocp
      vars:
        aio_host_ip_address: "{{ hostvars['hypervisor']['public_ip_address'] }}"
      when: ocp4_aio_deploy_type == 'ipi'

- name: Deploy SNO clusters if SNO is defined
  hosts: hypervisor
  tasks:
    - name: deploy SNO
      include_role:
        name: ocp4_aio_deploy_ocp
      when: ocp4_aio_deploy_type == 'sno'
      
- name: Deploy Roles if infra_workloads defined
  hosts:
    - bastion-vm
  gather_facts: false
  run_once: false
  become: true
  tags:
    - infra_workloads
  tasks:
    - name: apply infra workloads roles on nodes
      when:
        - infra_workloads | default("") | length > 0
      block:
        - name: Apply role "{{ workload_loop_var }}" on nodes
          include_role:
            name: "{{ workload_loop_var }}"
          vars:
            ACTION: "provision"
          loop: "{{ infra_workloads.split(',') | list }}"
          loop_control:
            loop_var: workload_loop_var
            
- name: Software flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Software checks completed successfully"
