---
- import_playbook: ../../setup_runtime.yml

- name: Set up environment for destroy
  hosts: localhost
  connection: local
  become: false
  tasks:
    - name: Set facts for ssh provision SSH key
      include_role:
        name: create_ssh_provision_key
      when:
        - ssh_provision_key_name is undefined

    - name: Locate environment SSH key
      include_role:
        name: locate_env_authorized_key

    - name: Get private SSH key from keyvault
      include_role:
        name: infra-azure-ssh-key

    - name: Run infra-azure-create-inventory role
      include_role:
        name: infra-azure-create-inventory

    - name: SSH config setup
      when:
        - groups["bastions"] is defined
        - groups["bastions"] | length > 0
      include_role:
        name: infra-common-ssh-config-generate

- name: Set ssh extra args for all hosts, use ssh_config just created
  hosts: all
  gather_facts: false
  any_errors_fatal: true
  ignore_errors: false
  tasks:
    - name: add -F option ansible_ssh_extra_args
      set_fact:
        ansible_ssh_extra_args: "{{ ansible_ssh_extra_args|default() }} -F {{ hostvars['localhost'].ansible_ssh_config }}"


