---
- name: Step 000 Pre Infrastructure
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tags:
    - step001
    - pre_infrastructure
  tasks:
    - debug:
        msg: "Step 000 Pre Infrastructure"
    - name: Azure Pre Infrastructure tasks
      when: cloud_provider == 'azure'
      block:
      - name: if windows_password is not defined, generate one
        when: windows_password is not defined
        block:
        - name: Generate windows Administrator password if not already defined
          command: openssl rand -base64 25
          register: password_gen_r
        - name: set_fact generated_windows_password (just generated)
          set_fact:
            generated_windows_password: "{{ password_gen_r.stdout }}"

- name: Add the Azure user to the Subscription
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  environment:
    AZURE_CLIENT_ID: "{{ azure_service_principal }}"
    AZURE_SUBSCRIPTION_ID: "{{ azure_subscription_id }}"
    AZURE_SECRET: "{{ azure_password }}"
    AZURE_TENANT: "{{ azure_tenant }}"
    AZURE_CONFIG_DIR: "{{ azure_config_dir }}"
  tasks:
    - name: Run the azure add user to subscription
      include_role:
        name: open-env-azure-add-user-to-subscription
