---
- name: Step 00xxxxx post software
  hosts: localhost
  gather_facts: false
  become: true
  tags:
    - step005

  tasks:
        
    - name: "Post-Software tasks Started"
      ansible.builtin.debug:
        msg: "Post-Software tasks Started"

- name: Run post_software_validation playbook
  when: >-
    agd_post_software_validation | default(false) | bool
      or agd_validation | default(false) | bool
  ansible.builtin.import_playbook: post_software_validation.yml
  tags:
    - post_software_validation
    - agd_validation

- name: PostSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:

    - name: "Post-Software checks completed successfully"
      ansible.builtin.debug:
        msg: "Post-Software checks completed successfully"

...
