---

- name: Step 00xxxxx software
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  collections:
    - awx.awx
  environment:
    CONTROLLER_HOST: "{{ ate_base_data.controller_host }}"
    CONTROLLER_USERNAME: "{{ ate_base_data.controller_username }}"
    CONTROLLER_PASSWORD: "{{ ate_base_data.controller_password }}"
    CONTROLLER_VERIFY_SSL: False

  tasks:

    - name: "Software tasks Started"
      ansible.builtin.debug:
        msg: "Binder Software tasks Started"

    - name: Configure AAP2 Controller and Hub
      when: controller_configuration_dispatcher_roles is defined
      ansible.builtin.include_role:
        name: infra.controller_configuration.dispatch

    - name: "Software checks completed successfully"
      ansible.builtin.debug:
        msg: "Software checks completed successfully"
      tags:
        - post_flight_check
...
