---
# The IPA host for VCenter
vc_ipa_host: ipa1.example.com
# Username with permission to create users on IPA
vc_ipa_user: someadminuser
# Password for the previous user
vc_ipa_pass: somepassword
#guid: sandbox-1234ab                
# Generated password for the user to be created in IPA
#vcenter_domain: vc.opentlc.com
# Role name for the sandbox user
vcenter_role: "Sandbox User"                                                      
vcenter_permissions:
  Datacenter: SDDC-Datacenter
  ClusterComputeResource: Cluster-1
  Folder: "{{ env_type }}-{{ guid }}"
  Datastore: WorkloadDatastore
  Network: segment-{{ env_type }}-{{ guid }}
vcenter_hosts:
- 54.81.187.115
- 54.209.236.136

