---
- name: Ensure VMC instances are running
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ vcenter_datacenter }}"
    cluster: "{{ vcenter_cluster }}"
    folder: "/Workloads/{{env_type}}-{{ guid }}"
    name: "{{ item.instance.hw_name }}"
    state: poweredon
    wait_for_ip_address: true 
  when: item.instance.hw_is_template != True
  loop: "{{ r_vmc_instances.results|default([]) }}"
