- name: Check if the AMI exists
  ec2_ami_info:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    region: "{{ aws_region_final | default(aws_region) | default(region) | default('us-east-1')}}"
    filters:
      name: "{{ ec2_custom_image }}"
  register: r_ec2_ami_info


- name: Fail if AMI doesnt exist
  fail:
    msg: "{{ ec2_custom_image }} doesn't exist on AWS"
  when: r_ec2_ami_info.images | length == 0

- set_fact:
    custom_ami_images_ids: "{{custom_ami_images_ids|default({}) | combine ( {ec2_custom_image: r_ec2_ami_info.images.0.image_id}) }}"

- debug: var=custom_ami_images_ids
- set_fact:
    custom_ami_images_tags: "{{custom_ami_images_tags|default({}) | combine ( {ec2_custom_image: r_ec2_ami_info.images.0.tags}) }}"
- debug: var=custom_ami_images_tags
