---
- debug: var=ACTION
- debug: var=copy_tags_prefix
- name: Create AMI from instance
  include_tasks: "create_ami_from_instance.yml"
  register: r_ec2_copy_vm_disk_to_image_list
  loop: "{{ ec2_copy_vm_disk_to_image_list }}"
  loop_control:
    loop_var: ec2_copy_image
  when: ec2_copy_vm_disk_to_image_list|default([])|length > 0 and ACTION=="provision"

- name: Copy AMI to different regions
  include_tasks: "copy_ami_to_regions.yml"
  register: r_ec2_release_list
  loop: "{{ ec2_custom_images }}"
  loop_control:
    loop_var: ec2_release_image
  when: ec2_custom_images and ec2_release_images_zones and ec2_release_names and ACTION=="release"

- name: Find AMI from instance
  include_tasks: "find_ami_for_instance.yml"
  loop: "{{ ec2_custom_images }}"
  loop_control:
    loop_var: ec2_custom_image
  when: ec2_custom_images|default([])|length > 0 and ACTION=="find"
