---
- name: Step 004 - Software
  hosts: bastions
  gather_facts: false
  become: true
  tasks:
  - name: Debug ocp4-cluster software playbook
    debug:
      msg: "ocp4-cluster Software playbook"

- name: Configure httpd
  hosts: bastions
  become: true
  tasks:
    - name: Install httpd
      yum:
        name: httpd

    - name: Install mod_ssl
      yum:
        name: mod_ssl

    - name: Copy ssl.conf
      template:
        src: httpd/ssl.conf
        dest: /etc/httpd/conf.d/ssl.conf

    - name: Copy ocp.conf
      template:
        src: httpd/ocp.conf
        dest: /etc/httpd/conf.d/ocp.conf

    - name: Remove current EPEL
      dnf:
        name: "epel-release"
        state: absent

    - name: Enable EPEL
      dnf:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
        state: present
        disable_gpg_check: true

    - name: Allow SELinux rule to allow httpd to connect network
      shell: setsebool -P httpd_can_network_connect 1

    - name: Create virtualenv and install certbot
      command: "{{ item }}"
      loop:
        -  python3 -m venv /opt/certbot/
        - /opt/certbot/bin/pip install --upgrade pip
        - /opt/certbot/bin/pip install certbot certbot-dns-route53

    - name: Stop httpd 
      service:
        name: httpd
        state: stopped

    - name: Generate certificate using certbot
      command: /opt/certbot/bin/certbot certonly  --dns-route53 -d *.apps.{{ guid }}{{ subdomain_base_suffix }} -m josegonz@redhat.com --agree-tos -n
      environment:
        AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}"
        AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"
        AWS_DEFAULT_REGION: "{{aws_region_final|d(aws_region)}}"

      #command: certbot certonly  --standalone -d console-openshift-console.apps.{{ guid }}{{ subdomain_base_suffix }},oauth-openshift.apps.{{ guid }}{{ subdomain_base_suffix }} -m josegonz@redhat.com --agree-tos -n

    - name: Start and enable httpd
      service:
        name: httpd
        state: restarted
        enabled: yes

    - name: Unregister from satellite
      redhat_subscription:
        state: absent

    - name: Remove katello package
      yum:
        name: katello-ca-consumer*
        state: absent


- name: Step 004 - Software
  hosts: localhost
  tasks:
  - name: EC2 Post Infrastructure
    when: cloud_provider is match("ec2")
    block:
    - name: Set variable ocp4_installer_private_networks
      set_fact:
        ocp4_installer_private_subnets: "{{ cloudformation_out_final.stack_outputs.PrivateSubnetOutput.split(',') }}"
      when: cloudformation_out_final|default(False)
