- name: Test website access
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Ensure website is accessible
      uri:
        url: "http://workstation.{{ subdomain_base }}"
        method: GET
      register: _result
      until: _result.status == 200
      retries: 12
      delay: 10

- name: Save AMI images from instances or RELEASE images
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create AMI from instances on build step
      import_role:
        name: infra-ec2-custom-images
      vars:
        ACTION: "create"
      when: purpose == "build"

    - name: Release AMI to different regions on release step
      import_role:
        name: infra-ec2-custom-images
      vars:
        ACTION: "release"
      when: purpose == "release"

- name: Output user access information
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Show website access information
      agnosticd_user_info:
        msg: "{{ item }}"
      loop:
        - " "
        - "You can access your lab using web: http://workstation.{{ subdomain_base }}"

    - name: Print Student SSH access as user.info
      agnosticd_user_info:
        msg: "{{ item }}"
      loop:
        - " "
        - "You can access your bastion via SSH:"
        - "SSH Access: ssh {{ student_name }}@workstation.{{ guid }}.{{ subdomain_base_suffix }}"
      when: install_student_user | bool

    - name: Print Student SSH password as user.info
      agnosticd_user_info:
        msg: "SSH password: {{ student_password | default(hostvars[groups.bastions.0].student_password) }}"
      when:
        - print_student_password | default(true) | bool
        - install_student_user | bool


- name: PostSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Post-Software checks completed successfully"
