---
#include /includes/aws-sandbox-meta.yaml
#include /includes/enterprise-premium-sla.yaml

# -------------------------------------------------------------------
# Platform
# -------------------------------------------------------------------
platform: RHPDS

# -------------------------------------------------------------------
# Mandatory Variables
# -------------------------------------------------------------------
env_type: ent-demo-ate-base
cloud_provider: ec2

aws_region: us-east-2

# Disable creating SSH key and bastion inventory (like skip-tags)
create_ssh_config: true

# -------------------------------------------------------------------
# AgnosticV meta variables
# -------------------------------------------------------------------
# AgnosticV Metadata
# Set VirtualEnv to run this config in
agnosticv_meta:
  babylon:
    kubeconfig: babylon-prod.kubeconfig
  deploy_with: babylon
  virtualenv: babylon
  params_to_variables:
    region: aws_region

sandbox_user_info_messages_enable: true
# -------------------------------------------------------------------
# Babylon meta variables
# -------------------------------------------------------------------

__meta__:
  aws_sandboxed: true
  anarchy:
    namespace: babylon-anarchy-enterprise
  deployer:
    virtualenv: ansible2.9-python3.6-2021-11-30
  catalog:
    namespace: babylon-catalog-{{ stage | default('?') }}
    display_name: ATE Base
    keywords:
    - ent-demo-ate
    labels:
      Product: Red_Hat_Ansible_Automation_Platform
      Product_Family: Red_Hat_Cloud
      Provider: RHDP
      Featured_Score: '90'
    parameters: []
  secrets:
  - name: ent-demo-ate
    namespace: gpte
  access_control:
    allow_groups:
    - babylon-admins
    - babylon-devs
    - rhpds-ate-demo-beta
    - rhpds-devs

repo_method: satellite
set_repositories_satellite_ha: True
set_repositories_satellite_url: labsat-ha.opentlc.com
set_repositories_satellite_org: Red_Hat_GPTE_Labs
set_repositories_satellite_activationkey: ent-demo-automate-the-enterprise
