---

- name: Step 000 Pre Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step000
    - pre_infrastructure
    - generate_env_keys

  tasks:

    - name: "Step 000 Pre Infrastructure"
      ansible.builtin.debug:
        msg: "Step 000 Pre Infrastructure"

- name: Run pre_infra_validation playbook
  when: agd_pre_infra_valdation | default(true) | bool
  ansible.builtin.import_playbook: pre_infra_validation.yml
  tags:
    - pre_infra_validation
    - agd_validation

...
