---
- name: Step 00xxxxx software
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - debug:
        msg: "Software tasks Started"

    - when: cloud_provider == 'vmc'
      include_tasks: software_vmc.yml

