---
- import_playbook: ../../setup_runtime.yml

- name: Destroy sandbox account 
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Remove the sandbox account access
      import_role:
        name: infra-vmc-sandbox
      vars:
        action: "destroy"
