---
- name: Step 00xxxxx post software
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - debug:
        msg: "Post-Software Steps starting"

    - name: user info for VMWare Cloud
      when: cloud_provider == 'vmc'


    - debug:
        msg: "Post-Software checks completed successfully"
