- hosts: localhost
  vars:
    - ocp4_workload_rhacs_install_operator_channel: "rhacs-3.73"
    - ocp4_workload_rhacs_install_operator_starting_csv: "rhacs-operator.v3.73.1"
    - ocp4_workload_rhacs_install_operator_use_catalog_snapshot: true
    - ocp4_workload_rhacs_central_admin_password: "prakhar"
  tasks:
  - include_role:
      name: ocp4_workload_rhacs
