---
vmc_project_name: "{{ env_type }}-{{ guid }}"


# SSH keys
ssh_key_path: "{{ output_dir }}/{{ guid }}_id_rsa"
ssh_provision_key_path : "{{ ssh_key_path }}"
ssh_pub_key_path: "{{ output_dir }}/{{ guid }}_id_rsa.pub"
ssh_provision_pubkey_path: "{{ ssh_pub_key_path }}"

# Naming of instances
vmc_instance_numeration: '%d'

# Delete device retry
vmc_delete_retries: 20
vmc_delete_delay: 60
