---
- import_playbook: ../include_vars.yml

- name: Delete Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: Install community.vmware collection for vmware modules
      command: >-
        ansible-galaxy collection install
        -p {{ playbook_dir }}/../collections community.vmware
        --force-with-deps

    - name: Run infra-dns Role
      when: cluster_dns_server is defined
      include_role:
        name: infra-dns
      vars:
        _dns_state: absent

    - name: Run infra-vmc-resources
      include_role:
        name: infra-vmc-resources
      vars:
        ACTION: destroy
